# Generated by Django 2.2.7 on 2020-04-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('password_salt', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('aspirant_id', models.AutoField(primary_key=True, serialize=False)),
                ('aspirant_photo', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=100)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('voter_reg_no', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('voter_password', models.CharField(max_length=255)),
                ('password_salt', models.CharField(max_length=255)),
                ('login_attempts', models.IntegerField(default=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.School')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voter')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('team_logo', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairman_id', to='api.Aspirant')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Election')),
                ('sec_gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec_gen_id', to='api.Aspirant')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_id', to='api.Aspirant')),
            ],
        ),
        migrations.AddField(
            model_name='aspirant',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voter'),
        ),
    ]
