# Generated by Django 2.2.7 on 2020-05-05 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='fname',
            field=models.CharField(default='Stephen', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspirant',
            name='lname',
            field=models.CharField(default='Mwangi', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Voter', unique=True),
        ),
    ]
