# Generated by Django 2.2.7 on 2020-03-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_password',
            field=models.BinaryField(max_length=255),
        ),
    ]
