# Generated by Django 2.2.7 on 2020-05-05 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200505_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirant',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Voter'),
        ),
    ]
