# Generated by Django 2.2.7 on 2020-03-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200314_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_password',
            field=models.BinaryField(editable=True, max_length=255),
        ),
    ]
