# Generated by Django 2.2.7 on 2020-03-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200314_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voter_password',
            field=models.CharField(max_length=255),
        ),
    ]
