# Generated by Django 2.2.7 on 2020-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200505_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slogan',
            field=models.TextField(default='Comerades Power'),
            preserve_default=False,
        ),
    ]
