# Generated by Django 2.2.7 on 2020-03-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200314_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='password_salt',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
