# Generated by Django 2.2.7 on 2020-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_team_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirant',
            name='message',
            field=models.TextField(default='Well, Helloooooo Internet!'),
            preserve_default=False,
        ),
    ]
