# Generated by Django 2.2.7 on 2020-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200314_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='login_attempts',
            field=models.IntegerField(default=10),
        ),
    ]
