# Generated by Django 2.2.7 on 2020-05-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200506_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='voter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Voter'),
        ),
        migrations.AlterField(
            model_name='team',
            name='chairman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_id', to='api.Aspirant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Election'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sec_gen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sec_gen_id', to='api.Aspirant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='treasurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_id', to='api.Aspirant'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Election'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Voter'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.School'),
        ),
    ]
