# Generated by Django 2.2.7 on 2020-03-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_voter_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='blockchain_address',
        ),
        migrations.AddField(
            model_name='aspirant',
            name='blockchain_address',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='end_timestamp',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_timestamp',
            field=models.TimeField(),
        ),
    ]
