# Generated by Django 2.2.7 on 2020-03-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200325_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
