# Generated by Django 2.2.7 on 2020-03-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200325_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='end_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='election',
            name='start_timestamp',
            field=models.DateTimeField(),
        ),
    ]
