# Generated by Django 2.2.7 on 2020-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_aspirant_blockchain_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('password_salt', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='aspirant_photo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.TextField(),
        ),
    ]
