# Generated by Django 2.2.7 on 2020-04-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200420_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirant',
            old_name='voter_id',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='chairman_id',
            new_name='chairman',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='election_id',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sec_gen_id',
            new_name='sec_gen',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='treasurer_id',
            new_name='treasurer',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='election_id',
            new_name='election',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='voter_id',
            new_name='voter',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='school_id',
            new_name='school',
        ),
    ]
