# Generated by Django 2.2.7 on 2020-03-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default='ds', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='password_salt',
            field=models.CharField(default='s', max_length=255),
            preserve_default=False,
        ),
    ]
