# Generated by Django 3.0.2 on 2020-03-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_auto_20200314_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
