# Generated by Django 2.2.7 on 2020-04-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0003_admin_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
